version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
    reviewers:
      - "px"
    assignees:
      - "px"
    rebase-strategy: auto
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
